arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - wrist_a_joint
     - elbow_joint
     - wrist_b_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      wrist_a_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_b_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10