/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/srv/GetLimits.srv
 *
 */


#ifndef DP_PTU47_MSGS_MESSAGE_GETLIMITSRESPONSE_H
#define DP_PTU47_MSGS_MESSAGE_GETLIMITSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dp_ptu47_msgs
{
template <class ContainerAllocator>
struct GetLimitsResponse_
{
  typedef GetLimitsResponse_<ContainerAllocator> Type;

  GetLimitsResponse_()
    : min_pan(0.0)
    , max_pan(0.0)
    , min_tilt(0.0)
    , max_tilt(0.0)  {
    }
  GetLimitsResponse_(const ContainerAllocator& _alloc)
    : min_pan(0.0)
    , max_pan(0.0)
    , min_tilt(0.0)
    , max_tilt(0.0)  {
    }



   typedef float _min_pan_type;
  _min_pan_type min_pan;

   typedef float _max_pan_type;
  _max_pan_type max_pan;

   typedef float _min_tilt_type;
  _min_tilt_type min_tilt;

   typedef float _max_tilt_type;
  _max_tilt_type max_tilt;




  typedef boost::shared_ptr< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GetLimitsResponse_

typedef ::dp_ptu47_msgs::GetLimitsResponse_<std::allocator<void> > GetLimitsResponse;

typedef boost::shared_ptr< ::dp_ptu47_msgs::GetLimitsResponse > GetLimitsResponsePtr;
typedef boost::shared_ptr< ::dp_ptu47_msgs::GetLimitsResponse const> GetLimitsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dp_ptu47_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dp_ptu47_msgs': ['/home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88a7086e2e0d3eaf8cd1546be520fe67";
  }

  static const char* value(const ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88a7086e2e0d3eafULL;
  static const uint64_t static_value2 = 0x8cd1546be520fe67ULL;
};

template<class ContainerAllocator>
struct DataType< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dp_ptu47_msgs/GetLimitsResponse";
  }

  static const char* value(const ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min_pan\n\
float32 max_pan\n\
float32 min_tilt\n\
float32 max_tilt\n\
\n\
\n\
";
  }

  static const char* value(const ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_pan);
      stream.next(m.max_pan);
      stream.next(m.min_tilt);
      stream.next(m.max_tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetLimitsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dp_ptu47_msgs::GetLimitsResponse_<ContainerAllocator>& v)
  {
    s << indent << "min_pan: ";
    Printer<float>::stream(s, indent + "  ", v.min_pan);
    s << indent << "max_pan: ";
    Printer<float>::stream(s, indent + "  ", v.max_pan);
    s << indent << "min_tilt: ";
    Printer<float>::stream(s, indent + "  ", v.min_tilt);
    s << indent << "max_tilt: ";
    Printer<float>::stream(s, indent + "  ", v.max_tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DP_PTU47_MSGS_MESSAGE_GETLIMITSRESPONSE_H
