/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/msg/PanTiltStamped.msg
 *
 */


#ifndef DP_PTU47_MSGS_MESSAGE_PANTILTSTAMPED_H
#define DP_PTU47_MSGS_MESSAGE_PANTILTSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dp_ptu47_msgs
{
template <class ContainerAllocator>
struct PanTiltStamped_
{
  typedef PanTiltStamped_<ContainerAllocator> Type;

  PanTiltStamped_()
    : header()
    , pan_angle(0.0)
    , tilt_angle(0.0)  {
    }
  PanTiltStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pan_angle(0.0)
    , tilt_angle(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pan_angle_type;
  _pan_angle_type pan_angle;

   typedef float _tilt_angle_type;
  _tilt_angle_type tilt_angle;




  typedef boost::shared_ptr< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PanTiltStamped_

typedef ::dp_ptu47_msgs::PanTiltStamped_<std::allocator<void> > PanTiltStamped;

typedef boost::shared_ptr< ::dp_ptu47_msgs::PanTiltStamped > PanTiltStampedPtr;
typedef boost::shared_ptr< ::dp_ptu47_msgs::PanTiltStamped const> PanTiltStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dp_ptu47_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dp_ptu47_msgs': ['/home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3f5136442fde435cbd84e5a0577ff74";
  }

  static const char* value(const ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3f5136442fde435ULL;
  static const uint64_t static_value2 = 0xcbd84e5a0577ff74ULL;
};

template<class ContainerAllocator>
struct DataType< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dp_ptu47_msgs/PanTiltStamped";
  }

  static const char* value(const ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 pan_angle\n\
float32 tilt_angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pan_angle);
      stream.next(m.tilt_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PanTiltStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dp_ptu47_msgs::PanTiltStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pan_angle: ";
    Printer<float>::stream(s, indent + "  ", v.pan_angle);
    s << indent << "tilt_angle: ";
    Printer<float>::stream(s, indent + "  ", v.tilt_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DP_PTU47_MSGS_MESSAGE_PANTILTSTAMPED_H
