/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/srv/SendTrajectory.srv
 *
 */


#ifndef DP_PTU47_MSGS_MESSAGE_SENDTRAJECTORYREQUEST_H
#define DP_PTU47_MSGS_MESSAGE_SENDTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dp_ptu47_msgs
{
template <class ContainerAllocator>
struct SendTrajectoryRequest_
{
  typedef SendTrajectoryRequest_<ContainerAllocator> Type;

  SendTrajectoryRequest_()
    : pan_angles()
    , tilt_angles()
    , tolerance(0.0)  {
    }
  SendTrajectoryRequest_(const ContainerAllocator& _alloc)
    : pan_angles(_alloc)
    , tilt_angles(_alloc)
    , tolerance(0.0)  {
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pan_angles_type;
  _pan_angles_type pan_angles;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _tilt_angles_type;
  _tilt_angles_type tilt_angles;

   typedef float _tolerance_type;
  _tolerance_type tolerance;




  typedef boost::shared_ptr< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SendTrajectoryRequest_

typedef ::dp_ptu47_msgs::SendTrajectoryRequest_<std::allocator<void> > SendTrajectoryRequest;

typedef boost::shared_ptr< ::dp_ptu47_msgs::SendTrajectoryRequest > SendTrajectoryRequestPtr;
typedef boost::shared_ptr< ::dp_ptu47_msgs::SendTrajectoryRequest const> SendTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dp_ptu47_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dp_ptu47_msgs': ['/home/brian/hydro_catkin_ws/smp_new/src/dp_ptu47_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79d4c65f94b1e57420856c9c3a059ffa";
  }

  static const char* value(const ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79d4c65f94b1e574ULL;
  static const uint64_t static_value2 = 0x20856c9c3a059ffaULL;
};

template<class ContainerAllocator>
struct DataType< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dp_ptu47_msgs/SendTrajectoryRequest";
  }

  static const char* value(const ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] pan_angles\n\
float32[] tilt_angles\n\
float32 tolerance\n\
";
  }

  static const char* value(const ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan_angles);
      stream.next(m.tilt_angles);
      stream.next(m.tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SendTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dp_ptu47_msgs::SendTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "pan_angles[]" << std::endl;
    for (size_t i = 0; i < v.pan_angles.size(); ++i)
    {
      s << indent << "  pan_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pan_angles[i]);
    }
    s << indent << "tilt_angles[]" << std::endl;
    for (size_t i = 0; i < v.tilt_angles.size(); ++i)
    {
      s << indent << "  tilt_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tilt_angles[i]);
    }
    s << indent << "tolerance: ";
    Printer<float>::stream(s, indent + "  ", v.tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DP_PTU47_MSGS_MESSAGE_SENDTRAJECTORYREQUEST_H
