# test module setup for the initial assembly simulations
modules:
 - id: sat_bus
   type: three_way
   root: true
 - id: module_a
   type: three_way
   root: false
   connections:
    - child_module: sat_bus
      parent_connector: 0
      child_connector: 2
    - child_module: flatbot_base
      parent_connector: 2
      child_connector: 0
 - id: module_b
   type: three_way
   root: false
   connections:
    - child_module: sat_bus
      parent_connector: 0
      child_connector: 1
 - id: extra_thing
   type: three_way
   root: false
   connections:
    - child_module: module_b
      parent_connector: 2
      child_connector: 1
 - id: flatbot_base
   type: arm
   root: false
 - id: flatbot_ee
   type: arm
   root: false